Carter/logging-v2
science-gpt/science-gpt pull request #49
Opened 2024-10-24 18:49 UTC by carterdemars

logging class

2024-10-24 20:10 UTC, bing1100 requested changes

2024-10-24 20:10 UTC, bing1100 commented on app/src/orchestrator/chat_orchestrator.py
> +        secrets = toml.load("../secrets.toml")
This will get fixed if u place secrets into the src folder - or else everyone one else will have to move our secrets out of src

2024-10-24 20:10 UTC, bing1100 commented on app/src/configs/user_config.yaml
Not a big deal, but if you are able to, let's copy the user_config file from the docker image so that SMEs don't have to remake accounts when we pull main from docker

2024-10-27 21:29 UTC, carterdemars commented on app/src/configs/user_config.yaml
rolled this back for now. let's do this in a future PR :)

2024-10-28 02:58 UTC, bing1100 approved these changes

2024-10-28 13:56 UTC, merged